services:
  - type: web
    name: hf-icu-mortality-risk-calculator
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 4 --timeout 120 -b 0.0.0.0:$PORT app:app
    healthCheckPath: /healthz
